# Generated by Django 5.2.4 on 2025-08-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
